### ISSUE TITLE
Add Alliance calculations

### ISSUE THREAD

**Issue by derpfacedirk** [avcordaro/mesbg-list-builder#1]
Alliance checking should be added.
I'm working on this in a fork atm. PR to follow soon.

What way should the alliance level be displayed?

**Comment by avcordaro** [comment]
Thank you for your help on this! I think that in terms of where to display the alliance level, ideally it would go in the dark header at the top of the page somewhere but that's already getting quite cluttered. Perhaps it can go in the whitespace just below the header, and above the list of warband cards (where the pop-up appears when you click "Export JSON"). That might also be a good place for any other info that needs to be displayed, such as illegal army alerts.

**Comment by derpfacedirk** [comment]
I think the white bar next to the warband display might also be a better position for that info

**Comment by derpfacedirk** [comment]
Also would you mind adding comments to your code
I'm not all that familiar with javascript in the first place so figuring things out is proving a bit tough without documentation

**Comment by avcordaro** [comment]
Absolutely! I've spent some time this evening adding comments to the code (and a bit of cleanup) . Let me know if you'd like any further commenting. 

I also agree with you about the position for this new info, the white bar could definitely be a good place for it too.
