### ISSUE TITLE
Ori and Óin missing from the Kindom of Moria list.

### ISSUE THREAD

**Issue by Matombo** [avcordaro/mesbg-list-builder#14]
According to Armies of The Lord of the Rings Balin can also take Ori and Óin vom teh Erebor Reclaimed Army list with him as Kindom of Moria Models, like with Gimli from the Fellowship.

**Comment by avcordaro** [comment]
Thanks again!

Fixed in v5.2.9. Ori and Oin are now available in the Kingdom of Moria list.
