### ISSUE TITLE
Kingdom of Moria Keyword

### ISSUE THREAD

**Issue by Matombo** [avcordaro/mesbg-list-builder#17]
Balins special rule says that every "Kazad-Dum" and "Erebor" Keyword is Replaced with "Moria" (aka giving the 3 reused Erebor heroes access to the "The Wealth of Moria lay not in Gold or Jewels, but in Mithril" special rule of the Army list).
Maybe add that as a note to the Army list?

**Comment by avcordaro** [comment]
I agree that's useful, I've added this extra detail alongside the army bonus info for Kingdom of Moria. Fixed in v5.2.10

Thank you!
