### ISSUE TITLE
Mumak warband starts with 1/12 instead of 0/12

### ISSUE THREAD

**Issue by Matombo** [avcordaro/mesbg-list-builder#18]
If i interpret the rules correctly neither the mumak nor the leader count torwards the 12 unit limit of the warband.

Which would also make sense as the howda can hold 12 units not counting the leader.

**Comment by Matombo** [comment]
this seems to happen on all mumak variants (normal one, war leader, and far harad)

**Comment by Matombo** [comment]
and also for the Great Beast of Gorgoroth (there it might not be relevant as the warband can only take the included archers anyway

**Comment by avcordaro** [comment]
Thanks, I've checked the rulebook again on this and you're correct. War Beasts count as two models, but the beast is not counted as part of the warband units. I've fixed this in v5.2.11. 

Thank you for reporting these bugs! I really appreciate it, do let me know if you find anything else.

**Comment by Matombo** [comment]
Giving back the thanks for writing the tool in the first place ^^.

Just writing down what I come acrose while using it.
