### ISSUE TITLE
The Dead of Dunharrow Rider of the Dead can lead Warbands

### ISSUE THREAD

**Issue by Matombo** [avcordaro/mesbg-list-builder#41]
"Additionally, warbands from this army that contain eight or more models, do not need a Hero to be the Captain of the Warband. Instead, one of the Warrior models within the warband takes on the role of the warband's Captain for the purpose of deployment."

I think "one of the Warrior models within" here is meant as the category Warrior vs Hero and not Warrior of the Dead, meaning 8 Riders of the Dead with one of the riders being the leader would also be a valid warband.

**Comment by mhollink** [comment]
I've create #46 to resolve this issue. @avcordaro will review the PR and when approved the the riders will be able to lead in the army list builder
