### ISSUE TITLE
The Dead of Dunharrow: Wrining when heroless warband has less then 8 modles

### ISSUE THREAD

**Issue by Matombo** [avcordaro/mesbg-list-builder#44]
The Dead of Dunharrow can have heroless warbands if they are at least 8 models big.

I think a warning could be usefull if you make a smaller heroless warband.

**Comment by mhollink** [comment]
With commit 97effa6 a message will be displayed to warn you about this issue;

> "Warband 2 needs to contain eight or more models before the Warrior of the Dead is able to lead them."

or

> "Warband 3 needs to contain eight or more models before the Rider of the Dead is able to lead them."
