### ISSUE TITLE
Herald of the Dead Heroic Actions

### ISSUE THREAD

**Issue by nygellyndley** [avcordaro/mesbg-list-builder#6]
Hi,
I'd add a commit myself but the cards folder doesn't seem to have the source image used to build.

The Herald of the Dead of The Dead of Dunharrow faction does not have Heroic Strike or Heroic March as shown on the roster card , in fact it's a 0 might hero.

Reference: Gondor at War p87.

Love this website btw, really useful as someone new to the game :)

**Comment by avcordaro** [comment]
Hi there,

Thanks for letting me know about the mistake with Heralds of the Dead. I've fixed their card in an update just now.

Really happy to hear you're enjoying the website!
