### ISSUE TITLE
Ability to drag and drop warriors within warbands

### ISSUE THREAD

**Issue by avcordaro** [avcordaro/mesbg-list-builder#65]

**Comment by mhollink** [comment]
There is a great NPM package that will make this easy to implement: `"@hello-pangea/dnd"`


There are some things to consider when implementing it:

1. Dropping a warrion in its origin warband should just reorder the warriors in the Warband. Which is quite easy...
2. Dropping a warrior with a specific warband enabled special option - should remove the option.
3. Dropping a warrior which is not a valid choice, such as a moria giant spider from Ashrak to Durbûrz.. or from an orc warband to an Uruk-Hai warband in one of the LL's - should just disable the droppable container.

**Comment by mhollink** [comment]
Another thing i was just thinking about:

4. Make sure bow limits and bow counts are properly moved around.
