### ISSUE TITLE
Request: Add Wounds Counter for Mounts

### ISSUE THREAD

**Issue by TheTanka** [avcordaro/mesbg-list-builder#74]
Some mounts have multiple wounds. For example the _War Board_ that _Dain Ironfoot, Lord of the Iron Hills_ can buy for 20 points.
Would it be possible to add wound counters for these mounts in the _Game Mode_. 
Possibly under the hero that has the mount.

Tested in Version v6.8.1

**Comment by mhollink** [comment]
Hey @TheTanka.

Thanks for raising this suggestion! Adding a wound counter for multi wound mounts is very much possible. A few profiles that come to mind for me are:

- The _War Board_ from _Dain Ironfoot_,
- The _Elk_ from _Thranduil_
- The _Sleigh_ OR _Eagle_  from _Radagast_
- _Shadowfax_ from _Gandalf the White_
- The _Cart_ of _Gandalf the Grey_


I'll see what I can do adding trackers for these.

**Comment by mhollink** [comment]
Version 6.9.0 was just deployed by Alex. This version includes the requested changes.

Happy list building!
